version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_REPOSITORY_FRONTEND_NAME}:release-${GITHUB_SHA}

  backend:
    build:
      context: ./backend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_REPOSITORY_BACKEND_NAME}:release-${GITHUB_SHA}

