name: Deploy to AWS

on:
  push:
    branches: [release]
  pull_request:

jobs:
  deploy:
    name: Build & Deploy with AWS Copilot
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS Copilot CLI
        run: |
          curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux \
          && chmod +x copilot-cli \
          && sudo mv copilot-cli /usr/local/bin/copilot

      - name: Initialize environment (only if not exists)
        run: |
          copilot env init --name production --region $AWS_REGION || echo "Env already exists"

      - name: Deploy frontend service
        run: copilot deploy --name frontend --env production

      - name: Deploy backend service
        run: copilot deploy --name backend --env production

